import { CodeExecutionSandboxSchema } from '../tools/CodeExecutionSandboxes/mutual';
import { RLMAgentEventsBody, RLMSubModel } from './orchestrator';

interface Sandbox {
    contextData: string,
    llmQuery: (inst: string, snip: string, modelIndex?: number) => Promise<string>,
    console: {
        log: (...args: any[]) => any,
        error: (...args: any[]) => any
    },
    submodels: Array<{model: any, instruction?: string}>,
    /** The storage for Context model answer */
    finalAnswer?: string,
    // A way for the agent to signal it has found the final answer
    submitFinalAnswer: (answer: string) => any
}

type CallLLMFunction = (prompt: string, modelIndex: number) => Promise<string>;

type EmitEventFunction = <Event extends keyof RLMAgentEventsBody>(eventName: Event, ...eventArgs: Parameters<RLMAgentEventsBody[Event]>) => any;

export class RLMEnvironment<CodeSandbox extends CodeExecutionSandboxSchema> {
    hugeContextData: string;
    submodels: RLMSubModel[];
    logs: string[];
    codeExecutionSandbox: CodeSandbox;
    callLLM: CallLLMFunction;
    emitEvent: EmitEventFunction;
    
    constructor(
        hugeContextData: string,
        submodels: RLMSubModel[],
        codeSandbox: CodeSandbox,
        callLLM: CallLLMFunction,
        emitEvent: EmitEventFunction
    ) {
        this.hugeContextData = hugeContextData;
        this.submodels = submodels;
        this.logs = [];
        this.codeExecutionSandbox = codeSandbox;
        this.callLLM = callLLM;
        this.emitEvent = emitEvent;
    }

    // This is the RECURSIVE function exposed to the LLM
    // Supports model selection for CodeAct pattern delegation
    async llmQuery(instruction: string, snippet: string, modelIndex: number = 0) {
        if (!this.callLLM) {
            throw new Error("callLLM function not initialized in RLMEnvironment");
        }

        // Validate model index
        if (modelIndex < 0 || modelIndex >= this.submodels.length) {
            console.warn(`Invalid model index ${modelIndex}, using default model 0`);
            modelIndex = 0;
        }

        const prompt = `${instruction}\n\nContext Snippet:\n${snippet}`;
        
        // Call the LLM with the selected sub-model
        // Sub-models typically use cheaper/faster variants than the orchestrator
        const response = await this.callLLM(
            prompt,
            modelIndex
        );
        
        return response;
    }

    // Executes the JS code generated by the Orchestrator
    async executeAgentCode(code: string) {
        this.logs = []; // Clear logs for this run
        this.emitEvent("execute_code_start", code);
        
        // Define the Sandbox context
        const sandbox: Sandbox = {
            contextData: this.hugeContextData,
            finalAnswer: undefined,
            submodels: this.submodels,
            llmQuery: (inst: string, snip: string, modelIndex?: number) => 
                this.llmQuery(inst, snip, modelIndex ?? 0),
            console: {
                log: (...args: any[]) => this.logs.push(args.join(' ')),
                error: (...args: any[]) => this.logs.push(`ERROR: ${args.join(' ')}`)
            },
            // A way for the agent to signal it has found the final answer
            submitFinalAnswer: (answer: string) => { sandbox.finalAnswer = answer; }
        };

        // Defined the output
        const executionOutputResult = await this.codeExecutionSandbox.execute(code, sandbox, this.logs);
        
        this.emitEvent("execute_code_end", executionOutputResult);

        return executionOutputResult;
    }
}
