import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		index: "src/index.ts",
		graph: "src/graph/index.ts",
		agents: "src/agent/public.ts",
		"agent/communication-protocols/index": "src/agent/communication-protocols/index.ts",
		"agent/communication-protocols/communicationProtocols/index": "src/agent/communication-protocols/communicationProtocols/index.ts",
		"agent/communication-protocols/queues/index": "src/agent/communication-protocols/queues/index.ts",
		"agent/RLM/index": "src/agent/RLM/index.ts",
		models: "src/models/index.ts",
		"models/server": "src/models/server.ts",
		"models/speech-to-text/index": "src/models/speech-to-text/index.ts",
		"models/text-to-speech/index": "src/models/text-to-speech/index.ts",
		"models/text-to-text/index": "src/models/text-to-text/index.ts",
		"models/embeddings/index": "src/models/embeddings/index.ts",
		"agent/tools/index": "src/agent/tools/index.ts",
		"agent/tools/mcp/index": "src/agent/tools/mcp/index.ts",
		"agent/tools/mcp/types": "src/agent/tools/mcp/types.ts",
		"agent/tools/hitl/index": "src/agent/tools/hitl/index.ts",
		"agent/skills/index": "src/agent/skills/index.ts",
		"agent/abstract/podcast/index": "src/agent/abstract/podcast/index.ts",
		"agent/skills/stores/index": "src/agent/skills/stores/index.ts",
		"agent/memory/index": "src/agent/memory/index.ts",
		"agent/abstract/aeval/index": "src/agent/abstract/aeval/index.ts",
		"agent/tools/CodeExecutionSandboxes/index": "src/agent/tools/CodeExecutionSandboxes/index.ts",
		"agent/plugins/index": "src/agent/plugins/index.ts",
		"agent/abstract/multianswers/index": "src/agent/abstract/multianswers/index.ts",
		"agent/abstract/agentsdebate/index": "src/agent/abstract/agentsdebate/index.ts",
		"agent/abstract/self-consistency/index": "src/agent/abstract/self-consistency/index.ts",
		"agent/abstract/sequential/index": "src/agent/abstract/sequential/index.ts",
		"augmented_generation/index": "src/augmented_generation/index.ts",
		"gacp/index": "src/gacp/index.ts",
		"chains/index": "src/chains/index.ts",
		"augmented_generation/rag/vector_databases/index": "src/augmented_generation/rag/vector_databases/index.ts",
		"augmented_generation/rag/vector_databases/chromadb/index": "src/augmented_generation/rag/vector_databases/chromadb/index.ts",
		"augmented_generation/rag/vector_databases/pinecone/index": "src/augmented_generation/rag/vector_databases/pinecone/index.ts",
		utils: "src/utils/files.ts",
		tools: "src/agent/tools/public.ts",
		browser: "src/browser.ts"
	},
	format: ["esm", "cjs"],
	dts: true,
	splitting: true,
	sourcemap: true,
	clean: true,
	outDir: "dist",
	target: "es2022",
	platform: "neutral",
	treeshake: true,
	external: [
		"node:*",
		"fs/promises",
		"fs",
		"path",
		"http",
		"https",
		"url",
		"util",
		"stream",
		"events",
		"buffer",
		"child_process",
		"module",
		"os",
		"crypto",
		"obsidian",
		"openai",
		"runpod-sdk",
		"@anthropic-ai/sdk",
		"@google/genai",
		"@modelcontextprotocol/sdk",
		"@e2b/code-interpreter",
		"zod"
	]
});